language: node_js
repo_token: wGINHV6S6PXhVJyHgEcU7S5XNY9DMgvey
service_name: travis-pro
before_install:
  - "npm install npm -g"
install:
  - npm install
node_js:
  - "stable"
script:
  - npm run cover
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"  